version: '3.3'

services:
  web:
    build:
      context: ../../  # текущая директория с Dockerfile
      dockerfile: docker/backend/Dockerfile
    container_name: itamityt_web
    restart: always
    env_file:
      - .env
    ports:
      - "8100:8100"
    command: uvicorn main:app --host 0.0.0.0 --port 8100
