# version: "3.9"

services:

  frontend:
    build:
      context: ../../
      dockerfile: dockers/frontend/Dockerfile

    container_name: itamityt_frontend

    ports:
      - "8081:80"

    restart: always