apiVersion: v1
kind: Secret
metadata:
  name: projectsecrets
  namespace: devspaceita
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://dbuser:userpasso@55.55.55.55:5432/dbname"
  SECRET_KEY: "your secret key"
