apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirect
  template:
    metadata:
      labels:
        app: redirect
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}

      containers:
        - name: redirect
          image: {{ .Values.redirect.image }}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: projectsecrets
