name: Build & Push Frontend (GHCR)

on:
  push:
    branches:
      - devfrontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:latest -f docker/frontend/Dockerfile .
      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}/frontend:latest